import { TypeChecking } from 'types/Task.types';

export const BOOSTLIST = [
	{
		id: 1,
		icon: '/assets/boost/multitap.jpg',
		title: 'multitap',
		subtitle: 'Get +1 coin per tap',
		price: 5000,
		style: {
			background: 'linear-gradient(180deg, #5ecdff 0%, #0a89ff 100%)',
		},
	},
	{
		id: 2,
		icon: '/assets/boost/max-energy.jpg',
		title: 'max energy',
		subtitle: 'Get +500 max energy',
		price: 5000,
		style: {
			background: 'linear-gradient(180deg, #ffc75a 0%, #fe7410 100%)',
		},
	},
	{
		id: 3,
		icon: '/assets/boost/tapbot.jpg',
		title: 'tap bot',
		subtitle: 'Get autoclicker for 12 hr',
		price: 100000,
		style: {
			background: 'linear-gradient(180deg, #c376ff 0%, #8308ff 100%)',
		},
	},
];

export const SHOPLIST = [
	{
		id: 1,
		img: '/assets/shop/exlusive.jpg',
		title: 'exclusive egg',
		subtitle: 'lvl 2—5',
		price: '100 ',
		isCoin: false,
	},
	{
		id: 2,
		img: '/assets/shop/random.jpg',
		title: 'random egg',
		subtitle: 'lvl 2—5',
		price: '90 ',
		isCoin: false,
	},
	{
		id: 3,
		img: '/assets/shop/stone.jpg',
		title: 'stone hammer',
		subtitle: '25% damage',
		price: '25 ',
		isCoin: false,
	},
	{
		id: 4,
		img: '/assets/shop/gold.jpg',
		title: 'gold hammer',
		subtitle: '75% damage',
		price: '50 ',
		isCoin: false,
	},
	{
		id: 5,
		img: '/assets/shop/diamond.jpg',
		title: 'diamond hammer',
		subtitle: '100% damage',
		price: '70 ',
		isCoin: false,
	},
];

export const BIRDLIST = [
	{
		id: 1,
		src: '/assets/inventory/Exclusive_1.jpg',
		title: 'Bird #1',
		tier: 'Exclusive',
	},
	{
		id: 2,
		src: '/assets/inventory/Exclusive_2.jpg',
		title: 'Bird #2',
		tier: 'Exclusive',
	},
	{
		id: 3,
		src: '/assets/inventory/Exclusive_3.jpg',
		title: 'Bird #3',
		tier: 'Exclusive',
	},


{
    id: 4,
    src: '/assets/inventory/Exclusive_4.jpg',
    title: 'Bird #4',
    tier: 'Exclusive',
},
{
    id: 5,
    src: '/assets/inventory/Exclusive_5.jpg',
    title: 'Bird #5',
    tier: 'Exclusive',
},
{
    id: 6,
    src: '/assets/inventory/Exclusive_6.jpg',
    title: 'Bird #6',
    tier: 'Exclusive',
},
{
    id: 7,
    src: '/assets/inventory/Exclusive_7.jpg',
    title: 'Bird #7',
    tier: 'Exclusive',
},
{
    id: 8,
    src: '/assets/inventory/Exclusive_8.jpg',
    title: 'Bird #8',
    tier: 'Exclusive',
},
{
    id: 9,
    src: '/assets/inventory/Exclusive_9.jpg',
    title: 'Bird #9',
    tier: 'Exclusive',
},
{
    id: 10,
    src: '/assets/inventory/Exclusive_10.jpg',
    title: 'Bird #10',
    tier: 'Exclusive',
},
{
    id: 11,
    src: '/assets/inventory/Tier 1_1.jpg',
    title: 'Bird #11',
    tier: 'Tier 1',
},
{
    id: 12,
    src: '/assets/inventory/Tier 1_2.jpg',
    title: 'Bird #12',
    tier: 'Tier 1',
},
{
    id: 13,
    src: '/assets/inventory/Tier 1_3.jpg',
    title: 'Bird #13',
    tier: 'Tier 1',
},
{
    id: 14,
    src: '/assets/inventory/Tier 1_4.jpg',
    title: 'Bird #14',
    tier: 'Tier 1',
},
{
    id: 15,
    src: '/assets/inventory/Tier 1_5.jpg',
    title: 'Bird #15',
    tier: 'Tier 1',
},
{
    id: 16,
    src: '/assets/inventory/Tier 1_6.jpg',
    title: 'Bird #16',
    tier: 'Tier 1',
},
{
    id: 17,
    src: '/assets/inventory/Tier 1_7.jpg',
    title: 'Bird #17',
    tier: 'Tier 1',
},
{
    id: 18,
    src: '/assets/inventory/Tier 1_8.jpg',
    title: 'Bird #18',
    tier: 'Tier 1',
},
{
    id: 19,
    src: '/assets/inventory/Tier 1_9.jpg',
    title: 'Bird #19',
    tier: 'Tier 1',
},
{
    id: 20,
    src: '/assets/inventory/Tier 1_10.jpg',
    title: 'Bird #20',
    tier: 'Tier 1',
},
{
    id: 21,
    src: '/assets/inventory/Tier 2_1.jpg',
    title: 'Bird #21',
    tier: 'Tier 2',
},
{
    id: 22,
    src: '/assets/inventory/Tier 2_2.jpg',
    title: 'Bird #22',
    tier: 'Tier 2',
},
{
    id: 23,
    src: '/assets/inventory/Tier 2_3.jpg',
    title: 'Bird #23',
    tier: 'Tier 2',
},
{
    id: 24,
    src: '/assets/inventory/Tier 2_4.jpg',
    title: 'Bird #24',
    tier: 'Tier 2',
},
{
    id: 25,
    src: '/assets/inventory/Tier 2_5.jpg',
    title: 'Bird #25',
    tier: 'Tier 2',
},
{
    id: 26,
    src: '/assets/inventory/Tier 2_6.jpg',
    title: 'Bird #26',
    tier: 'Tier 2',
},
{
    id: 27,
    src: '/assets/inventory/Tier 2_7.jpg',
    title: 'Bird #27',
    tier: 'Tier 2',
},
{
    id: 28,
    src: '/assets/inventory/Tier 2_8.jpg',
    title: 'Bird #28',
    tier: 'Tier 2',
},
{
    id: 29,
    src: '/assets/inventory/Tier 2_9.jpg',
    title: 'Bird #29',
    tier: 'Tier 2',
},
{
    id: 30,
    src: '/assets/inventory/Tier 2_10.jpg',
    title: 'Bird #30',
    tier: 'Tier 2',
},
{
    id: 31,
    src: '/assets/inventory/Tier 3_1.jpg',
    title: 'Bird #31',
    tier: 'Tier 3',
},
{
    id: 32,
    src: '/assets/inventory/Tier 3_2.jpg',
    title: 'Bird #32',
    tier: 'Tier 3',
},
{
    id: 33,
    src: '/assets/inventory/Tier 3_3.jpg',
    title: 'Bird #33',
    tier: 'Tier 3',
},
{
    id: 34,
    src: '/assets/inventory/Tier 3_4.jpg',
    title: 'Bird #34',
    tier: 'Tier 3',
},
{
    id: 35,
    src: '/assets/inventory/Tier 3_5.jpg',
    title: 'Bird #35',
    tier: 'Tier 3',
},
{
    id: 36,
    src: '/assets/inventory/Tier 3_6.jpg',
    title: 'Bird #36',
    tier: 'Tier 3',
},
{
    id: 37,
    src: '/assets/inventory/Tier 3_7.jpg',
    title: 'Bird #37',
    tier: 'Tier 3',
},
{
    id: 38,
    src: '/assets/inventory/Tier 3_8.jpg',
    title: 'Bird #38',
    tier: 'Tier 3',
},
{
    id: 39,
    src: '/assets/inventory/Tier 3_9.jpg',
    title: 'Bird #39',
    tier: 'Tier 3',
},
{
    id: 40,
    src: '/assets/inventory/Tier 3_10.jpg',
    title: 'Bird #40',
    tier: 'Tier 3',
},
{
    id: 41,
    src: '/assets/inventory/Tier 4_1.jpg',
    title: 'Bird #41',
    tier: 'Tier 4',
},
{
    id: 42,
    src: '/assets/inventory/Tier 4_2.jpg',
    title: 'Bird #42',
    tier: 'Tier 4',
},
{
    id: 43,
    src: '/assets/inventory/Tier 4_3.jpg',
    title: 'Bird #43',
    tier: 'Tier 4',
},
{
    id: 44,
    src: '/assets/inventory/Tier 4_4.jpg',
    title: 'Bird #44',
    tier: 'Tier 4',
},
{
    id: 45,
    src: '/assets/inventory/Tier 4_5.jpg',
    title: 'Bird #45',
    tier: 'Tier 4',
},
{
    id: 46,
    src: '/assets/inventory/Tier 4_6.jpg',
    title: 'Bird #46',
    tier: 'Tier 4',
},
{
    id: 47,
    src: '/assets/inventory/Tier 4_7.jpg',
    title: 'Bird #47',
    tier: 'Tier 4',
},
{
    id: 48,
    src: '/assets/inventory/Tier 4_8.jpg',
    title: 'Bird #48',
    tier: 'Tier 4',
},
{
    id: 49,
    src: '/assets/inventory/Tier 4_9.jpg',
    title: 'Bird #49',
    tier: 'Tier 4',
},
{
    id: 50,
    src: '/assets/inventory/Tier 4_10.jpg',
    title: 'Bird #50',
    tier: 'Tier 4',
},
{
    id: 51,
    src: '/assets/inventory/Tier 5_1.jpg',
    title: 'Bird #51',
    tier: 'Tier 5',
},
{
    id: 52,
    src: '/assets/inventory/Tier 5_2.jpg',
    title: 'Bird #52',
    tier: 'Tier 5',
},
{
    id: 53,
    src: '/assets/inventory/Tier 5_3.jpg',
    title: 'Bird #53',
    tier: 'Tier 5',
},
{
    id: 54,
    src: '/assets/inventory/Tier 5_4.jpg',
    title: 'Bird #54',
    tier: 'Tier 5',
},
{
    id: 55,
    src: '/assets/inventory/Tier 5_5.jpg',
    title: 'Bird #55',
    tier: 'Tier 5',
},
{
    id: 56,
    src: '/assets/inventory/Tier 5_6.jpg',
    title: 'Bird #56',
    tier: 'Tier 5',
},
{
    id: 57,
    src: '/assets/inventory/Tier 5_7.jpg',
    title: 'Bird #57',
    tier: 'Tier 5',
},
{
    id: 58,
    src: '/assets/inventory/Tier 5_8.jpg',
    title: 'Bird #58',
    tier: 'Tier 5',
},
{
    id: 59,
    src: '/assets/inventory/Tier 5_9.jpg',
    title: 'Bird #59',
    tier: 'Tier 5',
},
{
    id: 60,
    src: '/assets/inventory/Tier 5_10.jpg',
    title: 'Bird #60',
    tier: 'Tier 5',
},
{
    id: 61,
    src: '/assets/inventory/Tier 6_1.jpg',
    title: 'Bird #61',
    tier: 'Tier 6',
},
{
    id: 62,
    src: '/assets/inventory/Tier 6_2.jpg',
    title: 'Bird #62',
    tier: 'Tier 6',
},
{
    id: 63,
    src: '/assets/inventory/Tier 6_3.jpg',
    title: 'Bird #63',
    tier: 'Tier 6',
},
{
    id: 64,
    src: '/assets/inventory/Tier 6_4.jpg',
    title: 'Bird #64',
    tier: 'Tier 6',
},
{
	"id": 65,
	"src": "/assets/inventory/Tier 6_5.jpg",
	"title": "Bird #65",
	"tier": "Tier 6",
},
{
	"id": 66,
	"src": "/assets/inventory/Tier 6_6.jpg",
	"title": "Bird #66",
	"tier": "Tier 6",
},
{
	"id": 67,
	"src": "/assets/inventory/Tier 6_7.jpg",
	"title": "Bird #67",
	"tier": "Tier 6",
},
{
	"id": 68,
	"src": "/assets/inventory/Tier 6_8.jpg",
	"title": "Bird #68",
	"tier": "Tier 6",
},
{
	"id": 69,
	"src": "/assets/inventory/Tier 6_9.jpg",
	"title": "Bird #69",
	"tier": "Tier 6",
},
{
	"id": 70,
	"src": "/assets/inventory/Tier 6_10.jpg",
	"title": "Bird #70",
	"tier": "Tier 6",
},

];

export const TASKSLIST = [
	{
		id: 111,
		title: 'Выполните задания',
		description:
			'Это описание задания без максимумов, оно может быть любой длинный:',
		subtasks: [
			{
				id: 1,
				title: 'Подпишитесь на канал',
				url: '/assets/telegram.jpg',
				href: 'https://telegram.org/',
				isDone: false,
			},
			{
				id: 2,
				title: 'Вступите в чат',
				url: '/assets/youtube.jpg',
				href: 'https://www.youtube.com/',
				isDone: false,
			},
			{
				id: 3,
				title: 'Оставьте комментарий',
				url: '/assets/discord.jpg',
				href: 'https://discord.com/',
				isDone: false,
			},
		],
		url: '/assets/telegram.jpg',
		reward: 5000,
		checking: 'default' as TypeChecking,
		bannerUrl: '/assets/earn-more/Banner.jpg',
		bannerTitle: 'Описание чего-то',
		bannerDescription:
			'lorem ipsum dolor sit amet, consectetur adip e fits perfectly into lore m pointed to lorem ipsum dolor sit amet, consectetur adip e fits perfectly into lore m pointed to',
	},
	{
		id: 1,
		title: 'Это название задания',
		description: 'Это описание задания, здесь написано,',
		url: '/assets/youtube.jpg',
		href: 'https://www.youtube.com/',
		reward: 5000,
		checking: 'default' as TypeChecking,
		bannerUrl: '/assets/earn-more/Banner.jpg',
		bannerTitle: 'Описание чего-то',
		bannerDescription:
			'lorem ipsum dolor sit amet, consectetur adip e fits perfectly into lore m pointed to lorem ipsum dolor sit amet, consectetur adip e fits perfectly into lore m pointed to',
	},
	{
		id: 2,
		title: 'Подпишитесь на канал',
		description: 'подпишитесь',
		url: '/assets/discord.jpg',
		href: 'https://discord.com/',
		reward: 5000,
		checking: 'default' as TypeChecking,
		bannerUrl: '/assets/earn-more/Banner.jpg',
		bannerTitle: 'Описание чего-то',
		bannerDescription:
			'Это описание задания, здесь написано, что нужно сделать или написано об авторе, любой текст, который вы хотите. Макс высота 48пх пикселя.',
	},
	{
		id: 3,
		title: 'Это название задания',
		description: 'Это описание задания, здесь написано,',
		url: '/assets/telegram.jpg',
		href: 'https://telegram.org/',
		reward: 5000,
		checking: 'default' as TypeChecking,
		bannerUrl: '/assets/earn-more/Banner.jpg',
		bannerTitle: 'Описание чего-то',
		bannerDescription:
			'Это описание задания, здесь написано, что нужно сделать или написано об авторе, любой текст, который вы хотите. Макс высота 48пх пикселя.',
	},
	{
		id: 4,
		title: 'Подпишитесь на канал',
		description: 'подпишитесь',
		url: '/assets/youtube.jpg',
		href: 'https://www.youtube.com/',
		reward: 5000,
		checking: 'default' as TypeChecking,
		bannerUrl: '/assets/earn-more/Banner.jpg',
		bannerTitle: 'Описание чего-то',
		bannerDescription:
			'Это описание задания, здесь написано, что нужно сделать или написано об авторе, любой текст, который вы хотите. Макс высота 48пх пикселя.',
	},
];

export const FRIENDSLIST = [
	{
		id: 1,
		url: '',
		title: 'Vasya Voron',
		coin: 0,
	},
	{
		id: 2,
		url: '',
		title: 'Vasya Voron',
		coin: 500,
	},
	{
		id: 3,
		url: '',
		title: 'Vasya Voron',
		coin: 1000,
	},
	{
		id: 4,
		url: '',
		title: 'Vasya Voron',
		coin: 1500,
	},
	{
		id: 5,
		url: '',
		title: 'Vasya Voron',
		coin: 2000,
	},
	{
		id: 6,
		url: '',
		title: 'Vasya Voron',
		coin: 2500,
	},
	{
		id: 7,
		url: '',
		title: 'Vasya Voron',
		coin: 0,
	},
	{
		id: 8,
		url: '',
		title: 'Vasya Voron',
		coin: 500,
	},
	{
		id: 9,
		url: '',
		title: 'Vasya Voron',
		coin: 1000,
	},
	{
		id: 10,
		url: '',
		title: 'Vasya Voron',
		coin: 1500,
	},
	{
		id: 11,
		url: '',
		title: 'Vasya Voron',
		coin: 2000,
	},
	{
		id: 12,
		url: '',
		title: 'Vasya Voron',
		coin: 2500,
	},
];

export const testBird = [
	{
		id: 111,
		src: '/assets/inventory/bird 1.jpg',
		title: 'Bird #4',
		tier: 'Tier 1',
	},
	{
		id: 222,
		src: '/assets/inventory/Tier 2_1.jpg',
		title: 'Bird #4',
		tier: 'Tier 2',
	},
	{
		id: 333,
		src: '/assets/inventory/Tier 3_1.jpg',
		title: 'Bird #4',
		tier: 'Tier 3',
	},
	{
		id: 444,
		src: '/assets/inventory/Tier 4_1.jpg',
		title: 'Bird #4',
		tier: 'Tier 4',
	},
	{
		id: 555,
		src: '/assets/inventory/Tier 5_1.jpg',
		title: 'Bird #4',
		tier: 'Tier 5',
	},
	{
		id: 666,
		src: '/assets/inventory/Tier 5_1.jpg',
		title: 'Bird #4',
		tier: 'Tier 5',
	},
	{
		id: 777,
		src: '/assets/inventory/Exclusive_2.jpg',
		title: 'Bird #4',
		tier: 'Exclusive',
	},
];